# Generated by Django 2.0.6 on 2018-06-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('is_password', models.BooleanField(default=False)),
                ('uid', models.IntegerField()),
                ('gid', models.IntegerField()),
                ('fullname', models.CharField(max_length=100)),
                ('home', models.CharField(max_length=100)),
                ('shell', models.CharField(max_length=100)),
            ],
        ),
    ]
