# Generated by Django 2.0.6 on 2018-06-25 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=60)),
                ('insert', models.DateTimeField(default=django.utils.timezone.now)),
                ('update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
